/* ------------------------------------------------------------------
   data.js
   Builds the camera-roll list from the real files in /images.

   Everything a person edits by hand lives in three places below:
     1. COLLECTIONS      — collection names + each collection's cover image
     2. LIBRARY_COVER     — the cover image for the main "library" view
     3. METADATA          — one object per photo: caption, source,
                             location, date, kept-because, returned-to,
                             connection, type, and which collections it
                             belongs to

   Nothing else in this file needs to change to add real
   captions/dates/etc. — just fill in the fields below. Leave a field as
   "" if you haven't written it yet; it will simply show up blank.

   A small amount of *internal* randomness remains (hue/mood/subject/
   texture, card size, rotation) — it drives the wander layout and the
   "same mood" / "same subject" style suggestions in the isolation view,
   and is never shown to the viewer as metadata, so it's left alone.

   The rest of the app only depends on the shape of APP_DATA below —
   swap in more files or edit metadata without touching app.js.
------------------------------------------------------------------- */

(function () {

  // Seeded RNG so the *internal* layout/association values are stable
  // across reloads — only the wander layout re-randomizes on shuffle.
  function mulberry32(seed) {
    return function () {
      seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
      let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  const rng = mulberry32(20256);
  const rand = (min, max) => min + rng() * (max - min);
  const randInt = (min, max) => Math.floor(rand(min, max + 1));
  const pick = (arr) => arr[Math.floor(rng() * arr.length)];

  // The actual photos, dropped into /images. This list is kept in sync
  // with the contents of /images by hand — every file there should have
  // an entry here (and vice versa), whatever the current total is.
  const FILES = [
    "IMG_01.jpeg", "IMG_02.jpeg", "IMG_03.jpeg", "IMG_04.jpeg", "IMG_05.jpeg", "IMG_06.jpeg",
    "IMG_07.jpeg", "IMG_08.jpeg", "IMG_09.jpeg", "IMG_10.jpeg", "IMG_11.jpeg", "IMG_12.jpeg",
    "IMG_13.jpeg", "IMG_14.jpeg", "IMG_15.jpeg", "IMG_16.jpeg", "IMG_17.jpeg", "IMG_18.jpeg",
    "IMG_19.jpeg", "IMG_20.jpeg", "IMG_21.jpeg", "IMG_22.jpeg", "IMG_23.jpeg", "IMG_24.jpeg",
    "IMG_25.jpeg", "IMG_26.jpeg", "IMG_27.jpeg", "IMG_28.jpeg", "IMG_29.jpeg", "IMG_30.jpeg",
    "IMG_31.jpeg", "IMG_32.jpeg", "IMG_33.jpeg", "IMG_34.jpeg", "IMG_35.jpeg", "IMG_36.jpeg",
    "IMG_37.jpeg", "IMG_38.jpeg", "IMG_39.jpeg", "IMG_40.jpeg", "IMG_41.jpeg", "IMG_42.jpeg",
    "IMG_43.jpeg", "IMG_44.jpeg", "IMG_45.jpeg", "IMG_46.jpeg", "IMG_47.jpeg", "IMG_48.jpeg",
    "IMG_49.jpeg", "IMG_50.jpeg", "IMG_51.jpeg", "IMG_52.jpeg", "IMG_53.jpeg", "IMG_54.jpeg",
    "IMG_55.jpeg", "IMG_56.jpeg", "IMG_57.jpeg", "IMG_58.jpeg", "IMG_59.jpeg", "IMG_60.jpeg",
    "IMG_61.jpeg", "IMG_62.jpeg", "IMG_63.jpeg", "IMG_64.jpeg", "IMG_65.jpeg", "IMG_66.jpeg",
    "IMG_67.jpeg", "IMG_68.jpeg", "IMG_69.jpeg", "IMG_70.jpeg", "IMG_71.jpeg", "IMG_72.jpeg",
    "IMG_73.jpeg", "IMG_74.jpeg", "IMG_75.jpeg", "IMG_76.jpeg", "IMG_77.jpeg", "IMG_78.jpeg",
    "IMG_79.jpeg", "IMG_80.jpeg", "IMG_81.jpeg", "IMG_82.jpeg", "IMG_83.jpeg", "IMG_84.jpeg",
    "IMG_85.jpeg", "IMG_86.jpeg", "IMG_87.jpeg", "IMG_88.jpeg", "IMG_89.jpeg", "IMG_90.jpeg",
    "IMG_91.jpeg", "IMG_92.jpeg", "IMG_93.jpeg", "IMG_94.jpeg", "IMG_95.jpeg", "IMG_96.jpeg",
    "IMG_97.jpeg", "IMG_98.jpeg", "IMG_99.jpeg", "IMG_100.jpeg", "IMG_101.jpeg",
  ];

  // Internal tags — not shown as metadata, used only to drive the
  // "same mood" / "same subject" / "same texture" association logic in
  // the isolation view.
  const MOODS = ["quiet", "giddy", "tired", "cozy", "overstimulated", "nostalgic", "curious", "bored", "proud", "calm"];
  const SUBJECTS = ["hands", "sky", "food", "street", "plant", "screen", "pet", "reflection", "crowd", "object", "water", "light", "text", "shadow", "self", "sign"];
  const TEXTURES = ["grainy", "smooth", "blurry", "sharp", "warm", "cool", "dark", "bright", "soft", "harsh"];

  // ------------------------------------------------------------------
  // EDIT ME — collections + their cover images.
  // `cover` is a filename from /images, used as this collection's
  // thumbnail in the sidebar. Change it to whichever photo should
  // represent the collection.
  // ------------------------------------------------------------------
  const COLLECTIONS = [
    { id: "just-see", name: "JUST SEE WHAT HAPPENS [EXPERIMENTATION]", cover: "IMG_17.jpeg" },
    { id: "make-into", name: "MAKE IT INTO SOMETHING ELSE [IMAGINATION]", cover: "IMG_03.jpeg" },
    { id: "no-point", name: "NO POINT [?]", cover: "IMG_04.jpeg" },
    { id: "play-rules", name: "PLAY WITH THE RULES [BENDING SYSTEMS]", cover: "IMG_08.jpeg" },
    { id: "lose-track", name: "LOSE TRACK OF TIME [ABSORPTION]", cover: "IMG_01.jpeg" },
    { id: "play-together", name: "PLAY TOGETHER [SOCIAL PLAY]", cover: "IMG_13.jpeg" },
    { id: "what-else", name: "WHAT ELSE COULD IT BE? [POSSIBILITY]", cover: "IMG_19.jpeg" },
  ];

  // EDIT ME — cover image for the main "library" (all photos) view.
  const LIBRARY_COVER = "IMG_01.jpeg";

  // ------------------------------------------------------------------
  // EDIT ME — per-photo metadata, keyed by filename.
  // Every field is a plain string ("" if not filled in yet).
  //   caption      — a line about the photo
  //   type         — "primary" or "secondary" (not currently shown on the card)
  //   source       — where it came from (e.g. "iPhone 13", "screenshot")
  //   location     — where/when it was taken (e.g. "kitchen counter")
  //   date         — e.g. "Jun 3, 2024" (shown as typed, also used to
  //                  find photos from "around the same time")
  //   keptBecause  — why it's still around
  //   returnedTo   — how often you've come back to it (e.g. "3 times")
  //   connection   — what it reminds you of / what it's connected to
  //   collections  — array of collection ids (from COLLECTIONS above)
  //                  this photo belongs to; [] if none
  // ------------------------------------------------------------------
  const METADATA = {
    "IMG_01.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_17.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see"],
    },
    "IMG_18.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "lose-track"],
    },
    "IMG_02.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see"],
    },
    "IMG_03.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "lose-track"],
    },
    "IMG_04.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "play-rules", "what-else"],
    },
    "IMG_05.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_06.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_07.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into", "no-point", "what-else"],
    },
    "IMG_08.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-rules", "what-else"],
    },
    "IMG_09.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into"],
    },
    "IMG_10.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "what-else"],
    },
    "IMG_11.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see"],
    },
    "IMG_12.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "no-point"],
    },
    "IMG_13.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_14.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_15.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into", "play-rules"],
    },
    "IMG_16.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_19.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["what-else"],
    },
    "IMG_20.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track"],
    },
    "IMG_21.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_22.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_23.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_24.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_25.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_26.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into", "what-else"],
    },
    "IMG_27.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_28.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_29.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_30.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "play-rules"],
    },
    "IMG_31.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_32.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_33.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "no-point"],
    },
    "IMG_34.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_35.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see"],
    },
    "IMG_36.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_37.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_38.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see"],
    },
    "IMG_39.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track"],
    },
    "IMG_40.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track", "play-together"],
    },
    "IMG_41.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_42.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_43.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "play-rules"],
    },
    "IMG_44.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "lose-track"],
    },
    "IMG_45.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_46.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_47.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_48.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-together"],
    },
    "IMG_49.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_50.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into"],
    },
    "IMG_51.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "play-rules"],
    },
    "IMG_52.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "play-together"],
    },
    "IMG_53.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-together"],
    },
    "IMG_54.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track"],
    },
    "IMG_55.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track"],
    },
    "IMG_56.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_57.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_58.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "what-else"],
    },
    "IMG_59.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_60.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "lose-track"],
    },
    "IMG_61.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "play-rules", "what-else"],
    },
    "IMG_62.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "play-together"],
    },
    "IMG_63.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "play-rules"],
    },
    "IMG_64.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_65.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track"],
    },
    "IMG_66.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-rules"],
    },
    "IMG_67.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "lose-track"],
    },
    "IMG_68.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_69.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["just-see", "make-into", "play-rules"],
    },
    "IMG_70.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_71.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_72.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into"],
    },
    "IMG_73.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_74.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_75.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-rules", "play-together"],
    },
    "IMG_76.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-rules"],
    },
    "IMG_77.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "what-else"],
    },
    "IMG_78.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-together"],
    },
    "IMG_79.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point"],
    },
    "IMG_80.jpeg": {
      caption: "",
      type: "primary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["no-point", "lose-track"],
    },
    "IMG_81.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["lose-track", "play-together"],
    },
    "IMG_82.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["play-rules"],
    },
    "IMG_83.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-rules", "play-together"],
    },
    "IMG_84.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: ["make-into", "play-rules"],
    },
    "IMG_85.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_86.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_87.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_88.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_89.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_90.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_91.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_92.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_93.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_94.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_95.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_96.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_97.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_98.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_99.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_100.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
    "IMG_101.jpeg": {
      caption: "",
      type: "secondary",
      source: "",
      location: "",
      date: "",
      keptBecause: "",
      returnedTo: "",
      connection: "",
      collections: [],
    },
  };

  // ---------------------------------------------------------------
  // Below this line is app wiring — no need to edit for new photos or
  // metadata, only if the shape of the data itself changes.
  // ---------------------------------------------------------------

  const images = FILES.map((file, i) => {
    const meta = METADATA[file] || {};

    // Internal-only: card size + aspect placeholder (real aspect ratio
    // fills in once the image loads, see app.js preloadDimensions()).
    // Kept small overall, and large photos capped closer to medium so
    // the canvas stays airy rather than dominated by a few big cards.
    const sizeRoll = rng();
    const sizeBucket = sizeRoll < 0.36 ? "small" : sizeRoll < 0.76 ? "medium" : "large";
    const baseLong = sizeBucket === "small" ? randInt(85, 115) : sizeBucket === "medium" ? randInt(120, 155) : randInt(160, 200);

    const parsedDate = meta.date ? new Date(meta.date) : null;
    const hasDate = parsedDate && !isNaN(parsedDate);

    return {
      id: "img-" + i,
      index: i,
      file,
      code: file.replace(/\.[a-z0-9]+$/i, ""), // display name — the filename itself, no randomness

      // internal-only tags (association logic + wander layout only)
      hue: randInt(0, 359),
      mood: pick(MOODS),
      subject: pick(SUBJECTS),
      texture: pick(TEXTURES),

      baseLong, sizeBucket,
      w: baseLong, h: baseLong, // provisional square box until real dimensions load

      // manually-edited, displayed metadata (see METADATA above)
      caption: meta.caption || "",
      type: meta.type || "secondary",
      keptBecause: meta.keptBecause || "",
      source: meta.source || "",
      location: meta.location || "",
      dateLabel: meta.date || "",
      date: hasDate ? parsedDate : null,
      returnedTo: meta.returnedTo || "",
      connection: meta.connection || "",

      collections: meta.collections || [],
    };
  });

  window.APP_DATA = { images, collections: COLLECTIONS, libraryCover: LIBRARY_COVER };
})();
